In [5]:
import numpy as np
import pandas as pd
data = np.array([1,2,3])
data
type(data)

numpy.ndarray

In [7]:
data.dtype

dtype('int64')

In [8]:
data.ndim

1

In [10]:
data.size

3

In [ ]:
# ЛАБОРАТОРИЙН АЖИЛ No12 NUMPY САН

In [ ]:
# Дасгал 12.1.

In [11]:
import numpy as np
a = np.arange(1, 21)
a
b = np.arange(5, 51, 5) # бүхэл тоон массив үүсгэнэ
b.astype(np.float64) # бүхэл тоон массивыг бутархай тоонд хөрвүүлнэ b


array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [12]:
# Дасгал 12.2. 

In [13]:
a = np.array([1, 2, 3, 4], float) 
b = np.array([5, 6, 7, 8], float) 
print(np.add(a, b)) # a + b 
print(np.subtract(a, b)) # a – b 
print(np.multiply(a, b)) # a * b 
print(np.divide(a, b)) # a / b 
print(np.mod(a, b)) # a % b 
print(np.power(a, b)) # a ** b

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1. 2. 3. 4.]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [ ]:
# Дасгал 12.3. 

In [18]:
c = np.array([1, 5, 4, -8, 7, 9]) 
c[0], c[2], c[-1]
c[1 : 3]
c[2 : 5 : 2]
c[: : -1]

array([ 9,  7, -8,  4,  5,  1])

In [ ]:
# Дасгал 12.4.

In [20]:
d = np.array([[10, 45, -8], [11, 4, 56]]) 
d.ndim
d.shape
d.size
e = d.astype(np.float64) # бүхэл тоог бутархай болгоно 
e

array([[10., 45., -8.],
       [11.,  4., 56.]])

In [ ]:
# Дасгал 12.5.

In [21]:
np.arange(0, 15).reshape(3, 5) # 3 мөр, 5 баганатай 2D массив
np.arange(0, 15).reshape(5, 3) # 5 мөр, 3 баганатай 2D массив

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# Дасгал 12.6.

In [23]:
a = np.arange(4).reshape(2, 2) # 2 мөр, 2 баганатай 2D массив 
b = np.arange(5, 9).reshape(2, 2)
print(np.dot(a, b)) # матрицаар үржүүл
print(np.cross(a, b)) # матрицаар үржүүл

[[ 7  8]
 [31 36]]
[-5 -5]
